// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.glu.rpc.service;

import com.google.protobuf.UninitializedMessageException;

public final class RegisteServiceProto {
  private RegisteServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum FailureCause
      implements com.google.protobuf.ProtocolMessageEnum {
    DUPLICATE_USERNAME(0, 0),
    REGISTER_RPC_FAILED(1, 1),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static FailureCause valueOf(int value) {
      switch (value) {
        case 0: return DUPLICATE_USERNAME;
        case 1: return REGISTER_RPC_FAILED;
        default: return null;
      }
    }
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.glu.rpc.service.RegisteServiceProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final FailureCause[] VALUES = {
      DUPLICATE_USERNAME, REGISTER_RPC_FAILED, 
    };
    public static FailureCause valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private FailureCause(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.glu.rpc.service.RegisteServiceProto.getDescriptor();
    }
  }
  
  public static final class RegisteResult extends
      com.google.protobuf.GeneratedMessage {
    // Use RegisteResult.newBuilder() to construct.
    private RegisteResult() {}
    
    private static final RegisteResult defaultInstance = new RegisteResult();
    public static RegisteResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisteResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.glu.rpc.service.RegisteServiceProto.internal_static_com_glu_rpc_service_RegisteResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.glu.rpc.service.RegisteServiceProto.internal_static_com_glu_rpc_service_RegisteResult_fieldAccessorTable;
    }
    
    // optional bool success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean hasSuccess;
    private boolean success_ = false;
    public boolean hasSuccess() { return hasSuccess; }
    public boolean getSuccess() { return success_; }
    
    // optional .com.glu.rpc.service.FailureCause failure_cause = 2 [default = DUPLICATE_USERNAME];
    public static final int FAILURE_CAUSE_FIELD_NUMBER = 2;
    private boolean hasFailureCause;
    private com.glu.rpc.service.RegisteServiceProto.FailureCause failureCause_ = com.glu.rpc.service.RegisteServiceProto.FailureCause.DUPLICATE_USERNAME;
    public boolean hasFailureCause() { return hasFailureCause; }
    public com.glu.rpc.service.RegisteServiceProto.FailureCause getFailureCause() { return failureCause_; }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSuccess()) {
        output.writeBool(1, getSuccess());
      }
      if (hasFailureCause()) {
        output.writeEnum(2, getFailureCause().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSuccess()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getSuccess());
      }
      if (hasFailureCause()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getFailureCause().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.glu.rpc.service.RegisteServiceProto.RegisteResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.glu.rpc.service.RegisteServiceProto.RegisteResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.glu.rpc.service.RegisteServiceProto.RegisteResult result;
      
      // Construct using com.glu.rpc.service.RegisteServiceProto.RegisteResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.glu.rpc.service.RegisteServiceProto.RegisteResult();
        return builder;
      }
      
      protected com.glu.rpc.service.RegisteServiceProto.RegisteResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.glu.rpc.service.RegisteServiceProto.RegisteResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDescriptor();
      }
      
      public com.glu.rpc.service.RegisteServiceProto.RegisteResult getDefaultInstanceForType() {
        return com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.glu.rpc.service.RegisteServiceProto.RegisteResult build() {
        if (result != null && !isInitialized()) {
          throw new UninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.glu.rpc.service.RegisteServiceProto.RegisteResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.glu.rpc.service.RegisteServiceProto.RegisteResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.glu.rpc.service.RegisteServiceProto.RegisteResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.glu.rpc.service.RegisteServiceProto.RegisteResult) {
          return mergeFrom((com.glu.rpc.service.RegisteServiceProto.RegisteResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.glu.rpc.service.RegisteServiceProto.RegisteResult other) {
        if (other == com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasFailureCause()) {
          setFailureCause(other.getFailureCause());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSuccess(input.readBool());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.glu.rpc.service.RegisteServiceProto.FailureCause value = com.glu.rpc.service.RegisteServiceProto.FailureCause.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setFailureCause(value);
              }
              break;
            }
          }
        }
      }
      
      
      // optional bool success = 1;
      public boolean hasSuccess() {
        return result.hasSuccess();
      }
      public boolean getSuccess() {
        return result.getSuccess();
      }
      public Builder setSuccess(boolean value) {
        result.hasSuccess = true;
        result.success_ = value;
        return this;
      }
      public Builder clearSuccess() {
        result.hasSuccess = false;
        result.success_ = false;
        return this;
      }
      
      // optional .com.glu.rpc.service.FailureCause failure_cause = 2 [default = DUPLICATE_USERNAME];
      public boolean hasFailureCause() {
        return result.hasFailureCause();
      }
      public com.glu.rpc.service.RegisteServiceProto.FailureCause getFailureCause() {
        return result.getFailureCause();
      }
      public Builder setFailureCause(com.glu.rpc.service.RegisteServiceProto.FailureCause value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFailureCause = true;
        result.failureCause_ = value;
        return this;
      }
      public Builder clearFailureCause() {
        result.hasFailureCause = false;
        result.failureCause_ = com.glu.rpc.service.RegisteServiceProto.FailureCause.DUPLICATE_USERNAME;
        return this;
      }
    }
    
    static {
      com.glu.rpc.service.RegisteServiceProto.getDescriptor();
    }
    
    static {
      com.glu.rpc.service.RegisteServiceProto.internalForceInit();
    }
  }
  
  public static abstract class RegisteService
      implements com.google.protobuf.Service {
    protected RegisteService() {}
    
    public interface Interface {
      public abstract void checkDuplicateUserName(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request,
          com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done);
      
      public abstract void callRegister(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request,
          com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RegisteService() {
        @Override
        public  void checkDuplicateUserName(
            com.google.protobuf.RpcController controller,
            com.glu.rpc.service.UserProto.User request,
            com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done) {
          impl.checkDuplicateUserName(controller, request, done);
        }
        
        @Override
        public  void callRegister(
            com.google.protobuf.RpcController controller,
            com.glu.rpc.service.UserProto.User request,
            com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done) {
          impl.callRegister(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.checkDuplicateUserName(controller, (com.glu.rpc.service.UserProto.User)request);
            case 1:
              return impl.callRegister(controller, (com.glu.rpc.service.UserProto.User)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.glu.rpc.service.UserProto.User.getDefaultInstance();
            case 1:
              return com.glu.rpc.service.UserProto.User.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance();
            case 1:
              return com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void checkDuplicateUserName(
        com.google.protobuf.RpcController controller,
        com.glu.rpc.service.UserProto.User request,
        com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done);
    
    public abstract void callRegister(
        com.google.protobuf.RpcController controller,
        com.glu.rpc.service.UserProto.User request,
        com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.glu.rpc.service.RegisteServiceProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.checkDuplicateUserName(controller, (com.glu.rpc.service.UserProto.User)request,
            com.google.protobuf.RpcUtil.<com.glu.rpc.service.RegisteServiceProto.RegisteResult>specializeCallback(
              done));
          return;
        case 1:
          this.callRegister(controller, (com.glu.rpc.service.UserProto.User)request,
            com.google.protobuf.RpcUtil.<com.glu.rpc.service.RegisteServiceProto.RegisteResult>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.glu.rpc.service.UserProto.User.getDefaultInstance();
        case 1:
          return com.glu.rpc.service.UserProto.User.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance();
        case 1:
          return com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.glu.rpc.service.RegisteServiceProto.RegisteService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void checkDuplicateUserName(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request,
          com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.glu.rpc.service.RegisteServiceProto.RegisteResult.class,
            com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance()));
      }
      
      public  void callRegister(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request,
          com.google.protobuf.RpcCallback<com.glu.rpc.service.RegisteServiceProto.RegisteResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.glu.rpc.service.RegisteServiceProto.RegisteResult.class,
            com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.glu.rpc.service.RegisteServiceProto.RegisteResult checkDuplicateUserName(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request)
          throws com.google.protobuf.ServiceException;
      
      public com.glu.rpc.service.RegisteServiceProto.RegisteResult callRegister(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.glu.rpc.service.RegisteServiceProto.RegisteResult checkDuplicateUserName(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request)
          throws com.google.protobuf.ServiceException {
        return (com.glu.rpc.service.RegisteServiceProto.RegisteResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance());
      }
      
      
      public com.glu.rpc.service.RegisteServiceProto.RegisteResult callRegister(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request)
          throws com.google.protobuf.ServiceException {
        return (com.glu.rpc.service.RegisteServiceProto.RegisteResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.glu.rpc.service.RegisteServiceProto.RegisteResult.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_glu_rpc_service_RegisteResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_glu_rpc_service_RegisteResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData = 
      "\n\rregiste.proto\022\023com.glu.rpc.service\032\nus" +
      "er.proto\"n\n\rRegisteResult\022\017\n\007success\030\001 \001" +
      "(\010\022L\n\rfailure_cause\030\002 \001(\0162!.com.glu.rpc." +
      "service.FailureCause:\022DUPLICATE_USERNAME" +
      "*?\n\014FailureCause\022\026\n\022DUPLICATE_USERNAME\020\000" +
      "\022\027\n\023REGISTER_RPC_FAILED\020\0012\270\001\n\016RegisteSer" +
      "vice\022W\n\026checkDuplicateUserName\022\031.com.glu" +
      ".rpc.service.User\032\".com.glu.rpc.service." +
      "RegisteResult\022M\n\014callRegister\022\031.com.glu." +
      "rpc.service.User\032\".com.glu.rpc.service.R" +
      "egisteResultB,\n\023com.glu.rpc.serviceB\023Reg" +
      "isteServiceProtoH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_glu_rpc_service_RegisteResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_glu_rpc_service_RegisteResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_glu_rpc_service_RegisteResult_descriptor,
              new java.lang.String[] { "Success", "FailureCause", },
              com.glu.rpc.service.RegisteServiceProto.RegisteResult.class,
              com.glu.rpc.service.RegisteServiceProto.RegisteResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.glu.rpc.service.UserProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
