// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.glu.rpc.service;

import com.google.protobuf.UninitializedMessageException;

public final class LoginServiceProto {
  private LoginServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class LoginResult extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginResult.newBuilder() to construct.
    private LoginResult() {}
    
    private static final LoginResult defaultInstance = new LoginResult();
    public static LoginResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.glu.rpc.service.LoginServiceProto.internal_static_com_glu_rpc_service_LoginResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.glu.rpc.service.LoginServiceProto.internal_static_com_glu_rpc_service_LoginResult_fieldAccessorTable;
    }
    
    // optional bool success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean hasSuccess;
    private boolean success_ = false;
    public boolean hasSuccess() { return hasSuccess; }
    public boolean getSuccess() { return success_; }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSuccess()) {
        output.writeBool(1, getSuccess());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSuccess()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getSuccess());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.glu.rpc.service.LoginServiceProto.LoginResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.glu.rpc.service.LoginServiceProto.LoginResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.glu.rpc.service.LoginServiceProto.LoginResult result;
      
      // Construct using com.glu.rpc.service.LoginServiceProto.LoginResult.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.glu.rpc.service.LoginServiceProto.LoginResult();
        return builder;
      }
      
      protected com.glu.rpc.service.LoginServiceProto.LoginResult internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.glu.rpc.service.LoginServiceProto.LoginResult();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.glu.rpc.service.LoginServiceProto.LoginResult.getDescriptor();
      }
      
      public com.glu.rpc.service.LoginServiceProto.LoginResult getDefaultInstanceForType() {
        return com.glu.rpc.service.LoginServiceProto.LoginResult.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.glu.rpc.service.LoginServiceProto.LoginResult build() {
        if (result != null && !isInitialized()) {
          throw new UninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.glu.rpc.service.LoginServiceProto.LoginResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.glu.rpc.service.LoginServiceProto.LoginResult buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.glu.rpc.service.LoginServiceProto.LoginResult returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.glu.rpc.service.LoginServiceProto.LoginResult) {
          return mergeFrom((com.glu.rpc.service.LoginServiceProto.LoginResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.glu.rpc.service.LoginServiceProto.LoginResult other) {
        if (other == com.glu.rpc.service.LoginServiceProto.LoginResult.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSuccess(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional bool success = 1;
      public boolean hasSuccess() {
        return result.hasSuccess();
      }
      public boolean getSuccess() {
        return result.getSuccess();
      }
      public Builder setSuccess(boolean value) {
        result.hasSuccess = true;
        result.success_ = value;
        return this;
      }
      public Builder clearSuccess() {
        result.hasSuccess = false;
        result.success_ = false;
        return this;
      }
    }
    
    static {
      com.glu.rpc.service.LoginServiceProto.getDescriptor();
    }
    
    static {
      com.glu.rpc.service.LoginServiceProto.internalForceInit();
    }
  }
  
  public static abstract class LoginService
      implements com.google.protobuf.Service {
    protected LoginService() {}
    
    public interface Interface {
      public abstract void login(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request,
          com.google.protobuf.RpcCallback<com.glu.rpc.service.LoginServiceProto.LoginResult> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new LoginService() {
        @Override
        public  void login(
            com.google.protobuf.RpcController controller,
            com.glu.rpc.service.UserProto.User request,
            com.google.protobuf.RpcCallback<com.glu.rpc.service.LoginServiceProto.LoginResult> done) {
          impl.login(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.login(controller, (com.glu.rpc.service.UserProto.User)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.glu.rpc.service.UserProto.User.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.glu.rpc.service.LoginServiceProto.LoginResult.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void login(
        com.google.protobuf.RpcController controller,
        com.glu.rpc.service.UserProto.User request,
        com.google.protobuf.RpcCallback<com.glu.rpc.service.LoginServiceProto.LoginResult> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.glu.rpc.service.LoginServiceProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.login(controller, (com.glu.rpc.service.UserProto.User)request,
            com.google.protobuf.RpcUtil.<com.glu.rpc.service.LoginServiceProto.LoginResult>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.glu.rpc.service.UserProto.User.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.glu.rpc.service.LoginServiceProto.LoginResult.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.glu.rpc.service.LoginServiceProto.LoginService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void login(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request,
          com.google.protobuf.RpcCallback<com.glu.rpc.service.LoginServiceProto.LoginResult> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.glu.rpc.service.LoginServiceProto.LoginResult.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.glu.rpc.service.LoginServiceProto.LoginResult.class,
            com.glu.rpc.service.LoginServiceProto.LoginResult.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.glu.rpc.service.LoginServiceProto.LoginResult login(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.glu.rpc.service.LoginServiceProto.LoginResult login(
          com.google.protobuf.RpcController controller,
          com.glu.rpc.service.UserProto.User request)
          throws com.google.protobuf.ServiceException {
        return (com.glu.rpc.service.LoginServiceProto.LoginResult) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.glu.rpc.service.LoginServiceProto.LoginResult.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_glu_rpc_service_LoginResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_glu_rpc_service_LoginResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData = 
      "\n\013login.proto\022\023com.glu.rpc.service\032\nuser" +
      ".proto\"\036\n\013LoginResult\022\017\n\007success\030\001 \001(\0102T" +
      "\n\014LoginService\022D\n\005login\022\031.com.glu.rpc.se" +
      "rvice.User\032 .com.glu.rpc.service.LoginRe" +
      "sultB*\n\023com.glu.rpc.serviceB\021LoginServic" +
      "eProtoH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_glu_rpc_service_LoginResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_glu_rpc_service_LoginResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_glu_rpc_service_LoginResult_descriptor,
              new java.lang.String[] { "Success", },
              com.glu.rpc.service.LoginServiceProto.LoginResult.class,
              com.glu.rpc.service.LoginServiceProto.LoginResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.glu.rpc.service.UserProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
